name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - uses: actions/checkout@v1
      with:
        repository: https://github.com/XeroAPI/Xero-NetStandard.git 
    - name: generate csharp
      uses: docker://openapitools/openapi-generator-cli
      with:
        args: ./ci.sh
