name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
           dotnet-version: '2.2.103' 
    - name: Clone Xero-NetStandard
      if: success()
      run: |
            git clone https://github.com/kensan23/Xero-NetStandard.git
            cd Xero-NetStandard/
            git checkout oauth2
            git pull
    - name: generate csharp
      uses: docker://openapitools/openapi-generator-cli:v4.2.0
      with:
        args: ./generator/scripts/ci.sh    
    - name: build project
      if: success()
      run: |
          cd generator/output/csharp-netcore/accounting/src/Xero.NetStandard.OAuth2
          sudo dotnet build
    - name: Copy project
      if: success()
      run: |
          sudo cp -rf generator/output/csharp-netcore/accounting/src/Xero.NetStandard.OAuth2 Xero-NetStandard/
    - name: create branch
      if: success()
      run: |
          cd Xero-NetStandard/
          git config --global user.email "test@example.com"
          git config --global user.name "OpenApi Bot"
          git checkout -b openapi/${GITHUB_SHA::7}
          git add -A
          git commit -m "Changes from OpenAPI update"
          git push -u https://kensan23:${{ secrets.ACCESSTOKEN }}@github.com/kensan23/Xero-NetStandard.git openapi/${GITHUB_SHA::7}
          
          
          
          
          

