name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
           dotnet-version: '2.2.103' 
    - name: Clone Xero-NetStandard
      if: success()
      run: |
            git clone https://github.com/kensan23/Xero-NetStandard.git
            cd Xero-NetStandard/
            git checkout oauth2
            git pull
            pwd
    - name: generate csharp
      uses: docker://openapitools/openapi-generator-cli
      with:
        args: ./ci.sh    
    - name: build project
      if: success()
      run: |
          cd generator/output/csharp-netcore/accounting/src/Xero.NetStandard.OAuth2
          sudo dotnet build
    - name: Copy project
      if: success()
      run: |
          sudo cp -rf generator/output/csharp-netcore/accounting/src/Xero.NetStandard.OAuth2 Xero-NetStandard/
    - name: check difff
      if: success()
      run: |
          cd Xero-NetStandard/
          ls
          git diff
          

