name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: testclone
      if: success()
      run: git clone https://github.com/kensan23/Xero-NetStandard.git
    - name: generate csharp
      uses: docker://openapitools/openapi-generator-cli
      with:
        args: ./ci.sh
